@startuml

skinparam roundCorner 15

node app_server as "App server" {
  rectangle promtail as "Promtail" #ccbb33
  rectangle nginx as "Nginx"
  file logs_nginx as "Nginx logs"
  file logs_app as "Application logs"
  rectangle Application
}

node "Monitoring server" {
  rectangle loki as "Loki" #ff6644
}

Application --> logs_app : Пишет
nginx --> logs_nginx : Пишет
promtail --> loki : Отправляет логи
promtail --> logs_nginx : Читает
promtail --> logs_app :  Читает

@enduml
